API_KEY = 'ENTER YOUR API KEY HERE'
API_KEY_SECRET = 'ENTER YOUR API KEY SECRET HERE'
BEARER_TOKEN = 'ENTER YOUR BEARER TOKEN HERE'

ACCESS_TOKEN = 'ENTER YOUR ACCESS TOKEN HERE'
ACCESS_TOKEN_SECRET= 'ENTER YOUR ACCESS TOKEN SECRET HERE'

CLIENT_ID = 'ENTER YOUR CLIENT ID HERE'
CLIENT_SECRET = 'ENTER YOUR CLIENT SECRET HERE'